<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Chck.Mail.MailKit</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.18.0" />
    <PackageReference Include="MimeKit" Version="4.18.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chck.Mail.Core\Chck.Mail.Core.csproj" />
    <ProjectReference Include="..\Chck.Mail.Data\Chck.Mail.Data.csproj" />
  </ItemGroup>
</Project>
